---
title: "yangtiao"
output: github_document
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(plotly)
require(MASS)
require(ggplot2)
require(yangtiao)
require(rgl)
```

The R package can be use to calculate the value of B-spline basis，and provide 2D(`sin(x)` and `circular`) and 3D(`two dimensional density surface` and `sphere`) examples in the `demo` .


## Some examples' result diagram:

```{r echo=FALSE}

n=3
N=15
t <- seq(0,2*pi,0.01)
x <- cos(t)
y <- sin(t)
# t <- c(1:length(t))
# BaSplite(t,15,0,u)
# i=15
# sign(t>=u[i+1]&t<u[i+2])

u <- seq(-10,3*pi,length.out = N)
# u <- seq(-80,850,length.out = N)
X <- sapply(0:(length(u)-2-n),BaSplite,x=t,n=n,u=u)
mu <- tryCatch({
  solve(t(X)%*%X)%*%t(X)},
  error=function(e){
    MASS::ginv(t(X)%*%X)%*%t(X) #广义逆
  }
)
betax <- mu%*%x
betay <- mu%*%y
xx <- runif(1000,0,2*pi) #产生新的点
new <- sapply(0:(length(u)-2-n),BaSplite,x=xx,n=n,u=u)
newx <- new%*%betax #产生新的点
newy <- new%*%betay #产生新的点
p <- ggplot(data.frame(newx,newy),aes(newx,newy))+
  geom_point(size=0.5,color='red')
pp <- p+geom_path(data=data.frame(x=betax,y=betay),aes(x,y))+ # 控制点
  geom_text(data=data.frame(x=betax,y=betay),aes(x,y),label=c(0:(length(u)-2-n)),colour="blue",size=8)
pp+geom_point(data = data.frame(x,y),aes(x,y),size=0.5)


m=0
N=15
u <- seq(-2,3*pi,length.out = N)
t <- seq(0,2*pi,0.01)
n=3
X <- sapply(0:(length(u)-2-n-m),BaSplite,x=t,n,u)
y=sin(t)
betay <- solve(t(X)%*%X)%*%t(X)%*%y
betax <- solve(t(X)%*%X)%*%t(X)%*%t

new <- X%*%betay

ggplot(data = data.frame(x=t,y=new),aes(x,y))+geom_line()+
  geom_path(data=data.frame(t,y),aes(t,y),color='red')+
  geom_point(data=data.frame(betax,betay),aes(betax,betay))+
  geom_path(data=data.frame(betax,betay),aes(betax,betay))+
  geom_text(data=data.frame(x=betax,y=betay),aes(x,y),label=c(0:(length(u)-2-n)),colour="blue",size=5)
```
